server:
  port: 8082
spring:
  rabbitmq:
    host: 192.168.40.128
    port: 5672
    username: admin
    password: admin
  application:
    name: cloudribbon
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka